
import { SchemaField } from './types';

// Helper to create fields quickly
const createField = (id: string, name: string, description: string, prompt: string, strict: boolean = true, allowedValues: string[] = []): SchemaField => ({
  id, name, description, prompt, enabled: true, strict, allowedValues, isCustom: false
});

export const DEFAULT_SCHEMA: SchemaField[] = [
  createField('3', 'NOME SERIE', 'Famiglia del prodotto', 'Indica il nome della serie o collezione a cui appartiene il prodotto.', true),
  createField('4', 'TITOLO', 'Nome prodotto completo', 'Genera un titolo ottimizzato per e-commerce (Marca Modello Tipologia).', false),
  createField('5', 'DESCRIZIONE', 'Descrizione HTML', 'Scrivi una descrizione accattivante in HTML. Usa <b> per i punti chiave. Includi benefici.', false),
  createField('6', 'CATEGORIA 1', 'Macro Categoria', 'Categoria principale (es. Illuminazione Interno, Esterno).', true),
  createField('7', 'SOTTOCATEGORIA', 'Sotto Categoria', 'Specifica il tipo (es. Lampadario, Applique, Faretto).', true),
  createField('8', 'CATEGORIA 2', 'Categoria Specifica', 'Ulteriore dettaglio categoria se disponibile.', true),
  createField('9', 'AMBIENTE 1', 'Ambiente primario', 'Ambiente ideale (es. Cucina, Salotto, Giardino).', false),
  createField('10', 'AMBIENTE 2', 'Ambiente secondario', 'Altro ambiente adatto.', false),
  createField('11', 'STILE 1', 'Stile principale', 'Stile del design (es. Moderno, Classico, Industriale).', false),
  createField('12', 'STILE 2', 'Stile secondario', 'Altro stile correlato.', false),
  createField('13', 'FINITURA', 'Finitura superficiale', 'Tipo di finitura (es. Lucido, Opaco, Spazzolato).', true),
  createField('14', 'COLORE PRINCIPALE', 'Colore dominante', 'Colore principale del corpo lampada.', true),
  createField('15', 'COLORE 2', 'Colore secondario', 'Eventuale secondo colore o dettaglio.', true),
  createField('16', 'MATERIALI PRECISI', 'Lista materiali', 'Elenco dettagliato materiali (es. Alluminio pressofuso, Vetro soffiato).', true),
  createField('17', 'MATERIALE 1', 'Materiale principale', 'Materiale strutturale principale.', true),
  createField('18', 'MATERIALE 2', 'Materiale secondario', 'Materiale secondario.', true),
  createField('19', 'PESO NETTO', 'Peso in Kg', 'Peso del prodotto senza imballo (numero).', true),
  createField('20', 'CLASSE IP', 'Protezione IP', 'Grado di protezione IP (es. IP20, IP44, IP65).', true),
  createField('21', 'CLASSE ENERGETICA', 'Classe Energy Label', 'Classe efficienza energetica (A++, E, F, G).', true, ['A', 'B', 'C', 'D', 'E', 'F', 'G']),
  createField('22', 'CLASSE DI PROTEZIONE', 'Classe isolamento', 'Classe elettrica (I, II, III).', true, ['I', 'II', 'III']),
  createField('23', 'NUMERO LUCI', 'Quantità sorgenti', 'Numero di lampadine o punti led.', true),
  createField('24', 'TIPO LUCE', 'Attacco o LED', 'Tipo attacco (E27, E14, GU10) o LED Integrato.', true),
  createField('25', 'WATT', 'Potenza', 'Potenza massima o del LED in Watt.', true),
  createField('26', 'GRADAZIONE LUCE', 'Colore Luce Desc', 'Descrizione luce (Calda, Naturale, Fredda, RGB).', true),
  createField('27', 'GRADI K', 'Kelvin', 'Temperatura colore in Kelvin (es. 3000K, 4000K).', true),
  createField('28', 'LUMEN', 'Luminosità', 'Flusso luminoso in Lumen.', true),
  createField('29', 'LAMPADINA SOSTITUIBILE', 'Sostituibilità', 'La sorgente luminosa è sostituibile?', true, ['SI', 'NO']),
  createField('30', 'TIPO EMISSIONE', 'Direzione luce', 'Tipo emissione (Singola, Doppia, Diffusa).', true),
  createField('31', 'LAMPADINE INCLUSE', 'Incluso/Escluso', 'Le lampadine sono incluse nella confezione?', true, ['SI', 'NO']),
  createField('32', 'LUCE ORIENTABILE', 'Orientabile', 'Il fascio di luce è orientabile?', true, ['SI', 'NO']),
  createField('33', 'DIMMERABILE', 'Dimmerabile', 'Supporta regolazione intensità?', true, ['SI', 'NO']),
  createField('34', 'TENSIONE ALIMENTAZIONE', 'Voltaggio', 'Tensione (es. 220-240V).', true),
  createField('35', 'CORPO ALTEZZA REGOLABILE', 'Regolabile in altezza', 'Altezza regolabile?', true, ['SI', 'NO']),
  createField('36', 'CORPO ALTEZZA GENERALE', 'Altezza', 'Altezza corpo (cm).', true),
  createField('37', 'CORPO ALTEZZA MASSIMA', 'Alt. Max', 'Altezza massima estensione (cm).', true),
  createField('38', 'CORPO ALTEZZA MINIMA', 'Alt. Min', 'Altezza minima (cm).', true),
  createField('39', 'CORPO ALTEZZA CORPO', 'Alt. Solo Corpo', 'Altezza del solo corpo illuminante (cm).', true),
  createField('40', 'CORPO DIAMETRO', 'Diametro', 'Diametro totale (cm).', true),
  createField('41', 'CORPO LUNGHEZZA', 'Lunghezza', 'Lunghezza (cm).', true),
  createField('42', 'CORPO LARGHEZZA', 'Larghezza', 'Larghezza (cm).', true),
  createField('43', 'CORPO PROFONDITÀ', 'Profondità', 'Profondità/Sporgenza (cm).', true),
  createField('44', 'DIAMETRO ROSONE O FORO', 'Diam. Rosone', 'Diametro attacco a muro/soffitto (cm).', true),
  createField('45', 'ALTEZZA ROSONE', 'Alt. Rosone', 'Altezza/Spessore rosone (cm).', true),
  createField('46', 'LARGHEZZA ROSONE', 'Largh. Rosone', 'Larghezza rosone (cm).', true),
  createField('47', 'LUNGHEZZA ROSONE', 'Lungh. Rosone', 'Lunghezza rosone (cm).', true),
  createField('48', 'PROFONDITÀ ROSONE', 'Prof. Rosone', 'Profondità incasso (cm).', true),
  createField('49', 'COLORE ROSONE', 'Colore Rosone', 'Colore del rosone/base.', true),
  createField('50', 'MATERIALE ROSONE', 'Materiale Rosone', 'Materiale del rosone.', true),
  createField('51', 'PARALUME O DIFFUSORE ALTEZZA', 'Alt. Paralume', 'Altezza diffusore (cm).', true),
  createField('52', 'PARALUME O DIFFUSORE LARGHEZZA', 'Largh. Paralume', 'Larghezza diffusore (cm).', true),
  createField('53', 'PARALUME O DIFFUSORE LUNGHEZZA', 'Lungh. Paralume', 'Lunghezza diffusore (cm).', true),
  createField('54', 'PARALUME O DIFFUSORE DIAMETRO', 'Diam. Paralume', 'Diametro diffusore (cm).', true),
  createField('55', 'PARALUME O DIFFUSORE DIAMETRO INF', 'Diam. Inf', 'Diametro inferiore (cm).', true),
  createField('56', 'PARALUME O DIFFUSORE DIAMETRO SUP', 'Diam. Sup', 'Diametro superiore (cm).', true),
  createField('57', 'PARALUME O DIFFUSORE MATERIALE', 'Mat. Paralume', 'Materiale diffusore.', true),
  createField('58', 'PARALUME O DIFFUSORE COLORE', 'Col. Paralume', 'Colore diffusore.', true),
  createField('59', 'IMBALLO ALTEZZA', 'Alt. Imballo', 'Altezza confezione (cm).', true),
  createField('60', 'IMBALLO LARGHEZZA', 'Largh. Imballo', 'Larghezza confezione (cm).', true),
  createField('61', 'IMBALLO PROFONDITÀ', 'Prof. Imballo', 'Profondità confezione (cm).', true),
  createField('62', 'IMBALLO PESO KG', 'Peso Lordo', 'Peso incluso imballo (kg).', true),
  createField('63', 'IMBALLO VOLUME M2', 'Volume', 'Volume imballo (m3).', true),
  createField('64', 'FORMA', 'Forma principale del prodotto', 'Estrai la forma principale del prodotto basandoti sull\'analisi visiva dell\'immagine (es. Tonda, Rettangolare, Cilindrica).', false),
  createField('65', 'Misure_Generali', 'Riepilogo Dimensioni', 'Combina le dimensioni (Larghezza, Altezza, Profondità) in un formato standard es: "30x30x50 cm". Usa SOLO i valori numerici reali estratti.', false),
  createField('66', 'meta_keyword', 'Keywords SEO', 'Genera 5-8 keyword SEO pertinenti separate da virgola, basate sui dati del prodotto.', false),
  createField('67', 'meta_title', 'Meta Title', 'Genera un Meta Title ottimizzato SEO (max 60 caratteri) che includa Brand, Modello e Tipo.', false),
  createField('68', 'meta_description', 'Meta Description', 'Genera una Meta Description persuasiva (max 160 caratteri) con Call to Action, basata sulle specifiche.', false),
  createField('69', 'seo_keyword', 'Focus Keyword', 'Identifica la singola parola chiave SEO principale per questo prodotto.', false),
  createField('70', 'url_friendly', 'URL Slug', 'Genera uno slug URL friendly (tutto minuscolo, spazi sostituiti da trattini, niente caratteri speciali).', false),
  createField('71', 'Seo_H1', 'Intestazione H1', 'Genera un tag H1 ottimizzato (solitamente il nome completo del prodotto).', false),
  createField('72', 'Seo_H2', 'Intestazione H2', 'Genera un tag H2 che descriva i principali vantaggi o la categoria del prodotto.', false),
  createField('73', 'Seo_H3', 'Intestazione H3', 'Genera un tag H3 per introdurre le specifiche tecniche.', false),
  createField('74', 'image_title', 'Titolo Immagine', 'Genera un titolo descrittivo e SEO-friendly per l\'immagine principale.', false),
  createField('75', 'image_alt', 'Alt Text Immagine', 'Genera un testo alternativo (Alt Tag) che descriva visivamente il prodotto per l\'accessibilità.', false),
];

export const DEFAULT_TRUSTED_DOMAINS = [
  'amazon.it',
  'ebay.it',
  'trovaprezzi.it',
  'manomano.it',
  'leroymerlin.it'
];
